### ISSUE TITLE
Add command to give specific items

### ISSUE THREAD

**Issue by Verschlxfene** [CatgirlsServer/Issues#8]
`/give <item name> <count>`

Now that MC doesn't have arbitrary nbt data but structured data components, item filters can be done quite easily.

**Comment by NekosAreKawaii** [comment]
It's intentional that we don't have a /give <item name> <count> command to save ourselves the work to check if a item is exploitable on our server. /items should be enough for almost everything you want to test. It's not only about the data components / nbt data that we don't have the command. There are other reasons for that as well. If you think that there should be more items then just leave a comment with every item we should add to the /items command.
